---
stages:
  - build
  - Git Sync

build:
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t ${CI_REGISTRY_IMAGE}:latest .
    - docker push ${CI_REGISTRY_IMAGE}:latest
  stage: build
  tags:
    - docker-build
  except:
    - triggers

git-sync:
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | base64 -d)
    - git sync-remote
        git@github.com:bootc/PowerDNS-Admin.git
        git@git.boo.tc:bootc/PowerDNS-Admin.git
  stage: Git Sync
  image: dkr.boo.tc/bootc/github-gitlab-sync:latest
  tags:
    - docker
  only:
    - triggers

# vim: ft=yaml:sts=2:expandtab:sw=2:ts=2
